Fix build by adding /v4 to module path
achannarasappa/ticker pull request #260
Opened 2023-12-17 14:10 UTC by yonas

This PR will close:

- #252
- #208

2023-12-21 02:28 UTC, achannarasappa requested changes
Thanks for the pull request! I've added a few comments

Also please rebase with master. I've fixed the linting and test errors that were present when this branch was originally created so you should be able to get clearer automated feedback on the PR.

2023-12-21 02:28 UTC, achannarasappa commented on README.md
> +    <a href="https://github.com/achannarasappa/ticker/v4/releases"><img src="https://img.shields.io/github/v/release/achannarasappa/ticker" alt="Latest Release"></a>
URLs in the readme should remain without a `/v4/`

2023-12-21 02:28 UTC, achannarasappa commented on .goreleaser.yml
> +    homepage: "https://github.com/achannarasappa/ticker/v4"
This URL should remain without a `/v4/`

2023-12-21 02:28 UTC, achannarasappa commented on .goreleaser.yml
> +    homepage: https://github.com/achannarasappa/ticker/v4
This URL should remain without a `/v4/`

2023-12-21 02:28 UTC, achannarasappa commented on .goreleaser.yml
> +      - -s -w -X 'github.com/achannarasappa/ticker/v4/cmd.Version={{.Version}}'
Pretty sure these should remain with a `/v4/` but not certain. Have you run a test build to confirm this should be here?

2024-05-22 07:58 UTC, clausecker commented
Any progress on this one?

2024-06-02 19:12 UTC, achannarasappa commented
I think there might be some other issue causing problem here with `go install` but I've updated the module path.

2024-06-02 19:12 UTC, closed without merging